In [10]:
'''
 In the confusion matrix (CM) **for binary classification problem** in this case,
 Each row represents the actual class (The first row considers the first class, and the second row considers the second class)
 Each column represents a predicted class (the first column represents the prediction of the first class, and
 the second column represents the prediction of the second class)

The confusion matrix (CM) **for binary classification problem** in this case, 0 -> non-5s (negative class) & 1 -> 5s (positive class)

            Predicted
             0     1
          +------------
Actual  0 | TN    FP
        1 | FN    TP

Here,
        [[53892   687]
         [ 1891  3530]]

        The first row consideres no.of non-5 images (54579) (negative class wrt prediction) where,
          53892 of 54579 are correctly predicted as non-5s (i.e. no. of true negatives - TN)
          687 of 54579 are wrongly predicted as images of 5s (i.e. no. of false positives - FP)

        The second row considered no.of images of 5s (5421) (positive class wrt prediction) where,
          1891 of 5421 are wrongly predicted as non-5s (i.e no. of false negatives - FN)
          3530 of 5421 are correcly predicted as images of 5s (i.e. no. of true positives - TP)

A perfect classifier would only have true negatives and true positives

A confusion matrix can help us know the accuracy of predicting the positives (precision), i.e TP / (TP + FP)
But sometimes if the classifer always makes negative predictions and only one positive prediction on an instance its most
confident about (i.e FP = 0 & TP = 1), then the precision will be 1, but that is misleading, because the classifier ignores
many positive predictions of instances except for one of them. So precision is used along with 'recall' i.e. true positive rate (TPR)
or ratio of positive instances that are correctly detected i.e. TP / TP + FN

For example, when the model claims an image represents a 5, it is correct only 83.7% all the time (precision), but it only detects
only 65.1% of the 5s (recall)...:(

It os often convenient to combine precision and recall

'''
import numpy as np
import pandas as pd
from sklearn.datasets import fetch_openml
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix, precision_score, recall_score

mnist = fetch_openml('mnist_784', as_frame=False)
X, Y = mnist.data, mnist.target
X_train, Y_train, X_test, Y_test = X[:60000], Y[:60000], X[60000:], Y[60000:]

Y_train_5 = (Y_train == '5') # Need target labels with '5' from labels of training set
#print(Y_train_5)
Y_test_5 = (Y_test == '5') # Need target labels with '5' from labels of test set

model = SGDClassifier(random_state=42)

model.fit(X_train, Y_train_5) # Training model to classify images b/w '5' and 'non 5'

# Performing K-fold cross validation and returning the predictions made in each test fold
y_train_pred = cross_val_predict(model, X_train, Y_train_5, cv=3) # cross-validation is done on the training data only, and not using the final test data
print(f"Predicted labels made in each fold: {y_train_pred}\n")

# Getting the confusion matrix to evaluate the model's precision in predicting the targets of the training set (y_train_pred) with the true targets (Y_train_5)
cm = confusion_matrix(Y_train_5, y_train_pred)
print("confusion matrix of binary classifier: ")
print(cm)

# Precision of binary classifier
'''
tp = cm[1][1]
fp = cm[0][1]
precision = tp / (tp + fp)
'''
precision = precision_score(Y_train_5, y_train_pred)
print(f"precision of binary classifier in detecting images of 5s = {precision}")

# Recall of binary classifier
'''
tp = cm[1][1]
fn = cm[1][0]
recall = tp / (tp + fn)
'''
recall = recall_score(Y_train_5, y_train_pred)
print(f"recall of binary classifier in detecting images of 5s = {recall}")


y_train_pred_perfect = Y_train_5 # pretend the model classifies all images correctly
cm2 = confusion_matrix(Y_train_5, y_train_pred_perfect)
print("confusion matrix of perfect binary classifier: ")
print(cm2)

# Precision of perfect binary classifier
tp = cm2[1][1]
fp = cm2[0][1]
precision_perfect = tp / (tp + fp)
print(f"precision of perfect binary classifier in detecting images of 5s = {precision_perfect}") # 100% or 1.0

# Recall of perfect binary classifier
'''
tp = cm2[1][1]
fn = cm2[1][0]
recall_perfect = tp / (tp + fn)
'''
recall_perfect = recall_score(Y_train_5, y_train_pred_perfect)
print(f"recall of perfect binary classifier in detecting images of 5s = {recall}")



Predicted labels made in each fold: [ True False False ...  True False False]

confusion matrix of binary classifier: 
[[53892   687]
 [ 1891  3530]]
precision of binary classifier in detecting images of 5s = 0.8370879772350012
recall of binary classifier in detecting images of 5s = 0.6511713705958311
confusion matrix of perfect binary classifier: 
[[54579     0]
 [    0  5421]]
precision of perfect binary classifier in detecting images of 5s = 1.0
recall of perfect binary classifier in detecting images of 5s = 0.6511713705958311
